export const REQUEST_BUSINESS_INFO = 'REQUEST_BUSINESS_INFO';
export const CLEAR_BUSINESS_INFO = 'CLEAR_RECIPES';

export const REQUEST_ITEMS = 'REQUEST_ITEMS';
export const CLEAR_ITEMS = 'CLEAR_ITEMS';
export const REQUEST_SELECTED_ITEM = "REQUEST_SELECTED_ITEM";

export const REQUEST_ITEM_DETAIL = 'REQUEST_ITEM_DETAIL'; 

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';